server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /app
  tomcat:
    basedir: "tomcat"
    accesslog:
      enabled: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: http://localhost:8080/app/login/oauth2/code/google
  messages:
    basename: messages_ru
    encoding: UTF-8
minio:
  endpoint: http://localhost:9000
  access-key: ${S3_LOGIN}
  secret-key: ${S3_PASSWORD}
  bucket: photos
logging:
  level:
    root: INFO
    course.work: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n"